title: 沙盒管理系统
description: 沙盒管理系统官方文档
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  
github:
  is_project_page: false
  
sidebar:
  - name: 系统概述
    link: overview.html
  - name: 快速开始
    link: getting-started.html
  - name: 核心概念
    link: core-concepts.html
  - name: API参考
    link: api-reference.html
  - name: 最佳实践
    link: best-practices.html
  - name: 故障排除
    link: troubleshooting.html
  - name: 沙盒实例
    link: sandbox-instances.html
    children:
      - name: MCP工具
        link: instance/mcp.html
      - name: CDP实例
        link: instance/cdp.html
      - name: VNC实例
        link: instance/vnc.html 